number_list = [1, 2, 5, 1, 10, 14]
print(number_list)
number_list.append(40)
number_list.insert(1, 20)
print(number_list)
number_list.remove(2)
number_list.sort()
print(number_list)
number_list.reverse()
print(number_list)
print(1 in number_list)
print(12 in number_list)
print(number_list.count(1))
print(number_list.index(40))
number_list.pop()
number_list_2 = number_list.copy()
print(number_list_2)
number_list_2.clear()
print(number_list_2)
